apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: krxtxku44-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-9476799e24.3n6x.p3.openshiftapps.com/rhtap/rhtap-qe-go:33e4f8b4cf00f113d7797ac73ca7b478cfa739e8@sha256:dfbcfd0c223c14cea52f05f5a943a327aeb571bbda26d5690fc3e7dd2746598e
          name: container-image
